services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    platform: linux/amd64
    env_file:
      - .env
    expose:
      - 5000
    volumes:
      - ./logs:/app/logs
      - ./backend/temp_configs:/app/backend/temp_configs
      - ./backend/user_uploads:/app/backend/user_uploads
      - nmo_cache:/app/backend/data/neuromorpho
    networks:
      - app-network
    ulimits:
      nofile: 65536
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    ulimits:
      nofile: 65536
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    name: jardesigner_app-network

volumes:
  nmo_cache:
